global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'healthvoice-api'
    static_configs:
      - targets: ['healthvoice-api:80']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s

  - job_name: 'healthvoice-api-health'
    static_configs:
      - targets: ['healthvoice-api:80']
    metrics_path: '/health/ready'
    scrape_interval: 30s
    scrape_timeout: 10s 